echo "alias is='sudo apt install'" >> $HOME/.bashrc
echo "alias ud='sudo apt update'" >> $HOME/.bashrc
echo "alias ug='sudo apt upgrade'" >> $HOME/.bashrc
echo "alias udg='sudo apt update && sudo apt upgrade'" >> $HOME/.bashrc
echo "alias editbashrc='sudo nano $HOME/.bashrc'" >> $HOME/.bashrc
echo "alias editgrub='sudo nano /etc/default/grub'" >> $HOME/.bashrc
echo "alias scripts-nautilus='nautilus ~/Scripts'" >> $HOME/.bashrc
echo "alias shut='sudo shutdown -h now'" >> $HOME/.bashrc
echo "alias rebo='sudo reboot'" >> $HOME/.bashrc
echo "alias hib='sudo pm-hibernate'" >> $HOME/.bashrc
echo "alias create_sh_file='$HOME/Git/Linux-Scripts/create_sh_file.sh'" >> $HOME/.bashrc
echo "alias git_auto_push='$HOME/Git/Linux-Scripts/git_auto_push.sh'" >> $HOME/.bashrc
echo "alias ssh_interactive='$HOME/Git/Linux-Scripts/ssh_interactive.sh'" >> $HOME/.bashrc
echo "alias wget_unzip_interactive='$HOME/Git/Linux-Scripts/wget_unzip_interactive.sh'" >> $HOME/.bashrc
echo "alias unzip_interactive='$HOME/Git/Linux-Scripts/unzip_interactive.sh'" >> $HOME/.bashrc
echo "alias wget_interactive='$HOME/Git/Linux-Scripts/wget_interactive.sh'" >> $HOME/.bashrc
echo "alias unzip_tar_gz='tar -xzf'" >> $HOME/.bashrc
echo "alias directory_list='$HOME/Git/Linux-Scripts/directory_list.sh'" >> $HOME/.bashrc
